[package]
name = "urusername/wally-test" # replaced space with a dash
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"


[dependencies]
Knit = "sleitnick/knit@1.4.7"
janitor = "howmanysmall/janitor@1.15.1"
testez = "roblox/testez@0.4.1"
cmdr = "evaera/cmdr@1.9.0"
profileservice = "surnautica/profileservice@1.0.0"
React ="core-packages/react@17.0.1-rc.16"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
RoactSpring = "chriscerie/react-spring@1.1.3"