[package]
name = "urusername/wally-test" # replaced space with a dash
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"


[dependencies]
Knit = "sleitnick/knit@1.4.7"
testez = "roblox/testez@0.4.1"
cmdr = "evaera/cmdr@1.9.0"
ProfileService = "surnautica/profileservice@1.0.0"
React ="core-packages/react@17.0.1-rc.16"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
RoactSpring = "chriscerie/react-spring@1.1.3"
Timer = "sleitnick/timer@1.1.2"
Promise = "evaera/promise@4.0.0"
EnumList = "sleitnick/enum-list@2.0.1"
Concur = "sleitnick/concur@0.1.2"
GameAnalytics = "gameanalytics/gameanalytics-sdk@2.2.2"
Input = "sleitnick/input@2.1.1"
TableUtil = "sleitnick/table-util@1.2.0"
Red = "red-blox/red@2.0.0"